Add Support for custom theming
TheOdysseyJB/Odyssey pull request #15
Opened 2020-09-07 23:34 UTC by CharlieWhile13

_I was made to this by 23Aaron_

Custom Theming Support, for choosing your own images or animated background. Custom images just lets you choose from your photo library. For custom animated backgrounds, you choose the colours using Alderis. 

**Things to note beforehand**
- The fatalError on line 407 of ViewController.swift has been disabled, it kept crashing when opening a new view, it _seemed_ to function fine without. This may want to be looked into at some point
- Alderis has been bundled in a non-conventional way. I tried, for a long time, to get Cocoapods to like this project, but after many hours I couldn't. So as a temporary solution, the source files for Alderis have been bundled inside. 
- This has only been tested on my device, might want to test for bugs on other devices beforehand

2020-09-07 23:38 UTC, Diatrus requested changes
Would you mind adding in a small alert right before adding a custom background describing basically "This is a tribute, please don't be disrespectful."

2020-09-07 23:38 UTC, CharlieWhile13 commented
Yes, I'll do this now

2020-09-09 07:09 UTC, CharlieWhile13 commented
If you want an ipa you can download one [here](https://cdn.discordapp.com/attachments/725363874894708818/753138386801524756/Odyssey1.0.1-theme.ipa)

2020-09-10 12:02 UTC, Diatrus approved these changes

2020-09-10 12:02 UTC, merged